### ISSUE TITLE
HDFS cluster unstable in Kind

### ISSUE THREAD

**Issue by maltesander** [stackabletech/hdfs-operator#147]
The cluster created by the hdfs-operator sometimes has problems with kind  (namenode and therefore datanode do not start up, journalnode seems fine). This happens about 50% of the time. 

The namenode error:
```
2022-03-22 13:55:22,321 WARN common.Storage: Storage directory /data/name does not exist
2022-03-22 13:55:22,322 WARN namenode.FSNamesystem: Encountered exception loading fsimage
org.apache.hadoop.hdfs.server.common.InconsistentFSStateException: Directory /data/name is in an inconsistent state: storage directory does not exist or is not accessible.
```
The format-namenode container finishes successfully but has an exception as well:
```
2022-03-22 13:28:40,063 ERROR namenode.NameNode: Failed to start namenode.
java.lang.IllegalArgumentException: Unable to construct journal, qjournal://hdfs-journalnode-default-0.hdfs-journalnode-default.kuttl-test-flying-caribou.svc.cluster.local:8485/hdfs
	at org.apache.hadoop.hdfs.server.namenode.FSEditLog.createJournal(FSEditLog.java:1828)
	at org.apache.hadoop.hdfs.server.namenode.FSEditLog.initJournals(FSEditLog.java:296)
	at org.apache.hadoop.hdfs.server.namenode.FSEditLog.initJournalsForWrite(FSEditLog.java:261)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.format(NameNode.java:1209)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1673)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1783)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.apache.hadoop.hdfs.server.namenode.FSEditLog.createJournal(FSEditLog.java:1815)
	... 5 more
Caused by: java.net.UnknownHostException: hdfs-journalnode-default-0.hdfs-journalnode-default.kuttl-test-flying-caribou.svc.cluster.local:8485
	at org.apache.hadoop.hdfs.server.common.Util.getAddressesList(Util.java:378)
	at org.apache.hadoop.hdfs.qjournal.client.QuorumJournalManager.createLoggers(QuorumJournalManager.java:417)
	at org.apache.hadoop.hdfs.qjournal.client.QuorumJournalManager.createLoggers(QuorumJournalManager.java:199)
	at org.apache.hadoop.hdfs.qjournal.client.QuorumJournalManager.<init>(QuorumJournalManager.java:147)
	at org.apache.hadoop.hdfs.qjournal.client.QuorumJournalManager.<init>(QuorumJournalManager.java:126)
	... 10 more
2022-03-22 13:28:40,067 INFO util.ExitUtil: Exiting with status 1: java.lang.IllegalArgumentException: Unable to construct journal, qjournal://hdfs-journalnode-default-0.hdfs-journalnode-default.kuttl-test-flying-caribou.svc.cluster.local:8485/hdfs
```
The journal node looks fine. The datanode does not come up because of the namenode.

I am not sure if this is a race condition, a kind problem (because it seems to work fine in T2) or anything else. It is quite reproducible (@fhennig has the same problems). The format namenode fails and therefore the namenode shuts down. In the ZNode there is an empty directory for the hadoop-ha directory. So nothing written to zookeeper.

The problem happens on a fresh kind cluster as well on a "used" one (where hdfs was installed multiple times, in different namespaces or just default, with or without deleting the pvcs).

I attached the full logs:
[journalnode.log](https://github.com/stackabletech/hdfs-operator/files/8325049/journalnode.log)
[namenode.log](https://github.com/stackabletech/hdfs-operator/files/8325050/namenode.log)
[namenode-format-namenode-container.log](https://github.com/stackabletech/hdfs-operator/files/8325051/namenode-format-namenode-container.log)

We stumbled over this when testing the druid opa integration (the tests fail because of hdfs) as well as the pure kuttl hdfs tests in kind fail from time to time as well.

@lfrancke @soenkeliebau @razvan @backstreetkiwi do you guys have any idea?

**Comment by nightkr** [comment]
I have some memories of running into this with my old STFU HDFS operator as well.

From what I remember back then (and this seems to be corroborated by the logs you posted..) this is due to the NameNodes caching the DNS resolutions when trying to resolve the JournalNodes. This means that if all JNs aren't up (and considered `Ready`) by the time that the NNs try to start then the NNs get stuck in an invalid invalid state where they either fail completely (because all JNs fail to resolve) or only connect to a subset of the JNs.

I also had the same problem with DataNodes sometimes failing to find NNs.

In either case, I think the solution here would be to find where this caching comes from, and either turn it off completely or reduce it severely.

**Comment by maltesander** [comment]
I think that might be correct. We have a `java.net.UnknownHostException` (and that happens over and over even if the namenode container restarts).

**Comment by lfrancke** [comment]
See https://github.com/stackabletech/docker-images/issues/79 for reference

**Comment by maltesander** [comment]
fixed in https://github.com/stackabletech/hdfs-operator/pull/158
